[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools"]

[phases.install]
cmds = [
  "python3 -m pip install --user yt-dlp",
  "npm install"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "npm start"
